import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@/core/providers/ThemeProvider";
import { CoreModeToggle } from "@/core/components/CoreModeToggleComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <header className="flex justify-end p-2 border-b">
            <CoreModeToggle />
          </header>

          <main className="flex-1">{children}</main>

          <footer className="p-4 border-t">
            <h2>footer</h2>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
