import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex justify-between p-2 border-b">
            <div className="flex items-center gap-2">
              <h2 className="w-[200px] px-2 text-center bg-gray-200">LOGO</h2>
              <NavBar />
            </div>

            <div className="flex items-center px-2 gap-2">
              <h2>ICON</h2>
              <ModeToggle />
            </div>
          </header>

          <main className="flex-1">{children}</main>

          <footer className="p-4 border-t">
            <h2>footer</h2>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
