import "../globals.css";
import type { Metadata } from "next";
import { CoreNavBar } from "@/core/components/CoreNavBarComponent";
import { ThemeProvider } from "@/core/providers/ThemeProvider";
import { CoreModeToggle } from "@/core/components/CoreModeToggleComponent";
import { CoreSideMenu } from "@/core/components/CoreSideMenuComponent";
import { SwalConfirmProvider } from "@/core/providers/ConfirmDialogProvider";
import { Toaster } from "@/components/ui/sonner";
import { Gem } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const actualYear = new Date().getFullYear();

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <SwalConfirmProvider>
            <header className="flex justify-between p-2 border-b">
              <div className="flex items-center gap-2">
                <h2 className="ml-4 px-2 text-center">
                  <Gem />
                </h2>
                <CoreNavBar />
              </div>
              <div className="flex items-center px-2 gap-2">
                <CoreModeToggle />
                <CoreSideMenu />
              </div>
            </header>

            <main className="flex-1">{children}</main>

            <Toaster position="top-right" />

            <footer className="flex items-center p-2 border-t">
              <small>
                Desenvolvido por <b>Roger Pelissoni</b> ©{actualYear}
              </small>
            </footer>
          </SwalConfirmProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
